name: phrasewalk
description: "A crossword-like game about phrases."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  web: ^1.0.0
  url_launcher: ^6.3.0
  go_router: ^14.2.7
  provider: ^6.1.2

  soundpool: ^2.4.1
  
  yaml: ^3.1.2
  flutter_layout_grid: ^2.0.7
  stop_watch_timer: ^3.2.1

  mesh_gradient: ^1.3.7

  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Fraunces
      fonts:
        - asset: fonts/Fraunces.ttf
    - family: Fraunces-Italic
      fonts:
        - asset: fonts/Fraunces-Italic.ttf
